import IISAvtomatizaciya_zakupok7ЗаказПостEController from '../i-i-s-avtomatizaciya-zakupok7-заказ-пост-e';

var IISAvtomatizaciya_zakupok7ЗаказПостENewController = IISAvtomatizaciya_zakupok7ЗаказПостEController;
export default IISAvtomatizaciya_zakupok7ЗаказПостENewController;
