//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_zakupok7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сост поставок.
    /// </summary>
    // *** Start programmer edit section *** (СостПоставок CustomAttributes)

    // *** End programmer edit section *** (СостПоставок CustomAttributes)
    public enum СостПоставок
    {
        
        // *** Start programmer edit section *** (СостПоставок.НеОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостПоставок.НеОтгружен CustomAttributes)
        [Caption("НеОтгружен")]
        НеОтгружен,
        
        // *** Start programmer edit section *** (СостПоставок.ПолностьюОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостПоставок.ПолностьюОтгружен CustomAttributes)
        [Caption("ПолностьюОтгружен")]
        ПолностьюОтгружен,
        
        // *** Start programmer edit section *** (СостПоставок.ЧастичноОтгружен CustomAttributes)

        // *** End programmer edit section *** (СостПоставок.ЧастичноОтгружен CustomAttributes)
        [Caption("ЧастичноОтгружен")]
        ЧастичноОтгружен,
    }
}
