//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Avtomatizaciya_zakupok7
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч отчет.
    /// </summary>
    // *** Start programmer edit section *** (ТчОтчет CustomAttributes)

    // *** End programmer edit section *** (ТчОтчет CustomAttributes)
    [AutoAltered()]
    [Caption("Тч отчет")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчОтчетE", new string[] {
            "Цена as \'Цена\'",
            "ЭтоУслуга as \'Это услуга\'",
            "СуммаНДС as \'Сумма НДС\'",
            "Количество as \'Количество\'",
            "Сумма as \'Сумма\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Номенклатура as \'Номенклатура\'",
            "Номенклатура.Контрагенты.Контрагент as \'Контрагент\'"}, Hidden=new string[] {
            "Номенклатура.Номенклатура"})]
    [MasterViewDefineAttribute("ТчОтчетE", "Номенклатура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номенклатура")]
    public class ТчОтчет : ICSSoft.STORMNET.DataObject
    {
        
        private int fЦена;
        
        private bool fЭтоУслуга;
        
        private int fСуммаНДС;
        
        private int fКоличество;
        
        private int fСумма;
        
        private IIS.Avtomatizaciya_zakupok7.Номенклатура fНоменклатура;
        
        private IIS.Avtomatizaciya_zakupok7.ОтчетОЗак fОтчетОЗак;
        
        // *** Start programmer edit section *** (ТчОтчет CustomMembers)

        // *** End programmer edit section *** (ТчОтчет CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.Количество CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.Количество Get start)

                // *** End programmer edit section *** (ТчОтчет.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТчОтчет.Количество Get end)

                // *** End programmer edit section *** (ТчОтчет.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.Количество Set start)

                // *** End programmer edit section *** (ТчОтчет.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТчОтчет.Количество Set end)

                // *** End programmer edit section *** (ТчОтчет.Количество Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.Сумма CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.Сумма CustomAttributes)
        public virtual int Сумма
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.Сумма Get start)

                // *** End programmer edit section *** (ТчОтчет.Сумма Get start)
                int result = this.fСумма;
                // *** Start programmer edit section *** (ТчОтчет.Сумма Get end)

                // *** End programmer edit section *** (ТчОтчет.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.Сумма Set start)

                // *** End programmer edit section *** (ТчОтчет.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (ТчОтчет.Сумма Set end)

                // *** End programmer edit section *** (ТчОтчет.Сумма Set end)
            }
        }
        
        /// <summary>
        /// СуммаНДС.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.СуммаНДС CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.СуммаНДС CustomAttributes)
        public virtual int СуммаНДС
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.СуммаНДС Get start)

                // *** End programmer edit section *** (ТчОтчет.СуммаНДС Get start)
                int result = this.fСуммаНДС;
                // *** Start programmer edit section *** (ТчОтчет.СуммаНДС Get end)

                // *** End programmer edit section *** (ТчОтчет.СуммаНДС Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.СуммаНДС Set start)

                // *** End programmer edit section *** (ТчОтчет.СуммаНДС Set start)
                this.fСуммаНДС = value;
                // *** Start programmer edit section *** (ТчОтчет.СуммаНДС Set end)

                // *** End programmer edit section *** (ТчОтчет.СуммаНДС Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.Цена CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.Цена Get start)

                // *** End programmer edit section *** (ТчОтчет.Цена Get start)
                int result = this.fЦена;
                // *** Start programmer edit section *** (ТчОтчет.Цена Get end)

                // *** End programmer edit section *** (ТчОтчет.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.Цена Set start)

                // *** End programmer edit section *** (ТчОтчет.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (ТчОтчет.Цена Set end)

                // *** End programmer edit section *** (ТчОтчет.Цена Set end)
            }
        }
        
        /// <summary>
        /// ЭтоУслуга.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.ЭтоУслуга CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.ЭтоУслуга CustomAttributes)
        public virtual bool ЭтоУслуга
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.ЭтоУслуга Get start)

                // *** End programmer edit section *** (ТчОтчет.ЭтоУслуга Get start)
                bool result = this.fЭтоУслуга;
                // *** Start programmer edit section *** (ТчОтчет.ЭтоУслуга Get end)

                // *** End programmer edit section *** (ТчОтчет.ЭтоУслуга Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.ЭтоУслуга Set start)

                // *** End programmer edit section *** (ТчОтчет.ЭтоУслуга Set start)
                this.fЭтоУслуга = value;
                // *** Start programmer edit section *** (ТчОтчет.ЭтоУслуга Set end)

                // *** End programmer edit section *** (ТчОтчет.ЭтоУслуга Set end)
            }
        }
        
        /// <summary>
        /// Тч отчет.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Avtomatizaciya_zakupok7.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.Номенклатура Get start)

                // *** End programmer edit section *** (ТчОтчет.Номенклатура Get start)
                IIS.Avtomatizaciya_zakupok7.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ТчОтчет.Номенклатура Get end)

                // *** End programmer edit section *** (ТчОтчет.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.Номенклатура Set start)

                // *** End programmer edit section *** (ТчОтчет.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ТчОтчет.Номенклатура Set end)

                // *** End programmer edit section *** (ТчОтчет.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Avtomatizaciya_zakupok7.ОтчетОЗак.
        /// </summary>
        // *** Start programmer edit section *** (ТчОтчет.ОтчетОЗак CustomAttributes)

        // *** End programmer edit section *** (ТчОтчет.ОтчетОЗак CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage("ОтчетОЗак")]
        [TypeUsage(new string[] {
                "IIS.Avtomatizaciya_zakupok7.ЗаказПост",
                "IIS.Avtomatizaciya_zakupok7.ОтчетОЗак"})]
        public virtual IIS.Avtomatizaciya_zakupok7.ОтчетОЗак ОтчетОЗак
        {
            get
            {
                // *** Start programmer edit section *** (ТчОтчет.ОтчетОЗак Get start)

                // *** End programmer edit section *** (ТчОтчет.ОтчетОЗак Get start)
                IIS.Avtomatizaciya_zakupok7.ОтчетОЗак result = this.fОтчетОЗак;
                // *** Start programmer edit section *** (ТчОтчет.ОтчетОЗак Get end)

                // *** End programmer edit section *** (ТчОтчет.ОтчетОЗак Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчОтчет.ОтчетОЗак Set start)

                // *** End programmer edit section *** (ТчОтчет.ОтчетОЗак Set start)
                this.fОтчетОЗак = value;
                // *** Start programmer edit section *** (ТчОтчет.ОтчетОЗак Set end)

                // *** End programmer edit section *** (ТчОтчет.ОтчетОЗак Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчОтчетE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчОтчетE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчОтчетE", typeof(IIS.Avtomatizaciya_zakupok7.ТчОтчет));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчОтчет.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчОтчет CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчОтчет CustomAttributes)
    public class DetailArrayOfТчОтчет : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Avtomatizaciya_zakupok7.DetailArrayOfТчОтчет members)

        // *** End programmer edit section *** (IIS.Avtomatizaciya_zakupok7.DetailArrayOfТчОтчет members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчОтчет by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчОтчет.
        /// </summary>
        public DetailArrayOfТчОтчет(IIS.Avtomatizaciya_zakupok7.ОтчетОЗак fОтчетОЗак) : 
                base(typeof(ТчОтчет), ((ICSSoft.STORMNET.DataObject)(fОтчетОЗак)))
        {
        }
        
        public IIS.Avtomatizaciya_zakupok7.ТчОтчет this[int index]
        {
            get
            {
                return ((IIS.Avtomatizaciya_zakupok7.ТчОтчет)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Avtomatizaciya_zakupok7.ТчОтчет dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
