import IISAvtomatizaciya_zakupok7ОрганизацииEController from '../i-i-s-avtomatizaciya-zakupok7-организации-e';

var IISAvtomatizaciya_zakupok7ОрганизацииENewController = IISAvtomatizaciya_zakupok7ОрганизацииEController;
export default IISAvtomatizaciya_zakupok7ОрганизацииENewController;
