import IISAvtomatizaciya_zakupok7ПланЗакупокEController from '../i-i-s-avtomatizaciya-zakupok7-план-закупок-e';

var IISAvtomatizaciya_zakupok7ПланЗакупокENewController = IISAvtomatizaciya_zakupok7ПланЗакупокEController;
export default IISAvtomatizaciya_zakupok7ПланЗакупокENewController;
