import IISAvtomatizaciya_zakupok7НоменклатураEController from '../i-i-s-avtomatizaciya-zakupok7-номенклатура-e';

var IISAvtomatizaciya_zakupok7НоменклатураENewController = IISAvtomatizaciya_zakupok7НоменклатураEController;
export default IISAvtomatizaciya_zakupok7НоменклатураENewController;
